//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListViewApp.All.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListViewApp.All.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Léčivé přípravky.
        /// </summary>
        internal static string CuresPage_Cures {
            get {
                return ResourceManager.GetString("CuresPage_Cures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor.
        /// </summary>
        internal static string DoctorPage_Doctor {
            get {
                return ResourceManager.GetString("DoctorPage_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámky.
        /// </summary>
        internal static string NotesPage_Notes {
            get {
                return ResourceManager.GetString("NotesPage_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka pro pacienta.
        /// </summary>
        internal static string NotesPage_PatientNote {
            get {
                return ResourceManager.GetString("NotesPage_PatientNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka pro lékárníka.
        /// </summary>
        internal static string NotesPage_PharmacistNote {
            get {
                return ResourceManager.GetString("NotesPage_PharmacistNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacient.
        /// </summary>
        internal static string PatientPage_Patient {
            get {
                return ResourceManager.GetString("PatientPage_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vystaveno.
        /// </summary>
        internal static string PrescriptionDetailPage_Exposed {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Exposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PrescriptionDetailPage_ID {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_128.
        /// </summary>
        internal static string PrescriptionDetailPage_ID_128 {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_ID_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výdeje.
        /// </summary>
        internal static string PrescriptionDetailPage_Issues {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpisy.
        /// </summary>
        internal static string PrescriptionDetailPage_Listings {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Listings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recept.
        /// </summary>
        internal static string PrescriptionDetailPage_Prescription {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet opakování výdeje.
        /// </summary>
        internal static string PrescriptionDetailPage_Repetitions {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Identifikátor.
        /// </summary>
        internal static string PrescriptionDetailPage_SMS_ID {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_SMS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav receptu.
        /// </summary>
        internal static string PrescriptionDetailPage_State {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symboly.
        /// </summary>
        internal static string PrescriptionDetailPage_Symbols {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platnost od.
        /// </summary>
        internal static string PrescriptionDetailPage_Validity {
            get {
                return ResourceManager.GetString("PrescriptionDetailPage_Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
